### ISSUE TITLE
Small error in the code (tensorly.decomposition.parital_tucker)

### ISSUE THREAD

**Issue by dohe0342** [snudatalab/KegNet#3]
Hello, first of all thanks for good research.

There is a small error in the code.

KegNet/src/kegnet/utils/tucker.py  line 90-91:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/52394859/110287666-3e788680-802a-11eb-84ab-c10a43269e1c.png">

Third argument of decomp.partial_tucker is _**rank**_, not _**ranks**_.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/52394859/110287779-6962da80-802a-11eb-925e-b02037ee7829.png">

Thanks.

**Comment by jaeminyoo** [comment]
Thanks for the comment. The `ranks` option was in TensorLy 0.4.3 when we were writing the paper, but it seems the option is not available in the current version.
